# What should be the minimum and maximum enchantment level that is possible.
enchantment-level-range:
  min: 1
  max: 10
  # If you want to use vanilla's default min and max enchantment values, set this to true.
  use-default-limits: true

# How many enchantments should items receive.
total-enchants-on-items:
  min: 1
  max: 10

# Change which items will be enchanted when crafted.
items-to-be-enchanted:
  tools:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    bow: true
  armor:
    helmet: true
    chestplate: true
    leggings: true
    boots: true

# These materials will be excluded from being enchanted if set to false.
enabled-materials:
  wood: true
  stone: true
  iron: true
  diamond: true
  gold: true
  netherite: true

# Should we enchant regardless if the enchantment is for the tool/armor?
# This won't check if the enchantment is supported on the item.
# Example: sharpness on armor, silk touch on swords, etc.
# If you set this to false, you will get correct enchantments for items.
enchant-items-with-unsupported-enchants: true

# If you want to enchant everything you craft.
# All the checks for tools/armor/materials will be ignored.
enchant-everything: false

# No touch please :)
config-version: 4